### ISSUE TITLE
Font and characters used in GIF in Readme?

### ISSUE THREAD

**Issue by Asheq** [gcavallanti/vim-noscrollbar#5]
Font Monaco in iTerm2 doesn't display correctly using the recommended settings:

    %{noscrollbar#statusline(20,'■','◫',['◧'],['◨'])}

So I'm wondering what font you are using in the GIF. It looks so nice.

Thanks!

**Comment by gcavallanti** [comment]
It's Menlo. The easiest way for you to see the "retina" mode in action would be to turn on the `Use a different font for non-ASCII text` checkbox under `Preferences | Profiles | (your profile) | Text` and choose Menlo there.

**Comment by Asheq** [comment]
It looks great now, thanks!
